#pragma once

#include <stdint.h>

namespace tongdou {

enum class FaceAction : uint8_t {
  None,
  Sleep,
  WakeUp,
  Awake,
  Blink,
  Smile,
  Serious,
  RollEyes,
  Sleepy,
  Wronged,
  Squint,
  Innocent,
  Confused,
  Angry,
  Surprised,
  Shy,
  Fierce,
  Proud,
  Nervous,
  FirstSummonConfusedHold,
  AccountantPause,
  AccountantRoundEyes,
  AccountantSuspiciousSquint,
  AccountantCalculating,
  AccountantLedgerSearch,
  AccountantDebt3,
  AccountantDebtScratch,
  AccountantDebt2,
  AccountantDebtPi,
  AccountantSmugSquint,
};

enum class LightAction : uint8_t {
  None,
  Off,
  SoftWhite,
  WarmWake,
  RedShortBlink,
  WeakBreath,
  DimWarm,
  DimCyan,
  SummonCyanWake,
  SummonCyanHold,
  SummonCyanFocus,
  SummonPurpleApproach,
  SummonGoodFlash,
  SummonPurpleHold,
  SummonNightmareRise,
  SummonDrop,
  SummonNowFlash,
  SummonLaughBreath,
  SummonIdleCyan,
};

enum class MotionAction : uint8_t {
  None,
  Stop,
  Nod,
  TinyShake,
  NudgeForward,
  LeanForward,
  ShrinkBack,
  CheekyDance,
  CheekyDanceV2,
  TinyReluctantShake,
  TurnAwayToRear,
  RearWiggleLeft,
  RearWiggleRight,
  RearWiggleShowoff,
  HardBrakeStop,
  TurnBackToFront,
  SummonSpinBrake,
  SummonStretchBack,
  SummonLookAside,
  SummonReturnFromLook,
  SummonCreepForward,
  SummonGoodLunge,
  SummonHoldTilt,
  SummonReturnFromHold,
  SummonNightmareCreep,
  SummonNowLunge,
  SummonLaughWiggle,
  AccountantConfusedFidget,
  AccountantExtortLean,
  AccountantStubbornWiggle,
  TinySmugWiggle,
  SummonStartLunge,
};

enum class VoiceLine : uint8_t {
  None,
  WakeGreeting,
  SnoozeSoft,
  SnoozeTease,
  ConfirmReward,
  QuietReply,
  BreakReminder,
  OvertimeNudge,
  OvertimeCowardReply,
  ReminderDueNudge,
  LowBatteryWhine,
  ChargingRelief,
  RecognitionCoffeeChoke,
  DanceShowDomestic,
  DanceShowGlobal,
  DemoCheekyCalibrationDance,
  DemoNightGossipGlobal,
  DemoNightCowardGlobal,
  DemoMorningSoftGlobal,
  DemoRecordedEmailSummaryGlobal,
  DemoFirstSummonNightmare,
  DemoCrowdfundingCallGlobal,
  DemoConfusedAccountant,
  DemoAccountantClearDebt,
  DemoAccountantEmotionalDamage,
  DemoAccountantBribeAccepted,
  DemoAccountantSelectiveMemory,
  DemoAccountantPiDebt,
};

}  // namespace tongdou
