[platformio]
default_envs = esp32s3

[env:esp32s3]
platform = platformio/espressif32@6.10.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 460800
extra_scripts = post:tools/chunked_upload.py
board_build.flash_size = 4MB
board_build.partitions = huge_app.csv
board_build.flash_mode = dio
board_upload.flash_size = 4MB
build_flags =
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -Wall
  -Wextra
  -std=gnu++17
build_unflags =
  -std=gnu++11
